c_songs =  {...
"10 Miles High",...
"Even Deeper",...
"I'm Looking Forward To Joining You, Finally",...
"Into The Void",...
"La Mer",...
"No, You Don't",...
"Please",...
"Somewhat Damaged",...
"Starfuckers Inc_",...
"The Big Come Down",...
"The Day The World Went Away",...
"The Fragile",...
"The Great Below",...
"The New Flesh",...
"The Way Out Is Through",...
"The Wretched",...
"Underneath It All",...
"We're In This Together",...
"Where Is Everybody",...
}

disp(["Pistes à traiter: ",num2str(size(c_songs)(2))])
count_song = 1;
for ce_song = c_songs
    t_song = ce_song{1};
    disp(["    ",num2str(count_song)," ",t_song])
    count_song++;
    vocaux
end
